import type { SketchDescriptor } from "../types";

export const descriptor: SketchDescriptor = {
  id: "starTrails",
  label: "StarTrails",
  shortLabel: "StarTrails",
  description:
    "Light points orbiting a drifting vortex, each leaving a comet-like trail through simulated smoke (WebGPU/TSL).",
  colorPalette: {
    startColor: [120, 60, 255],
    midColor: [0, 200, 255],
    endColor: [255, 80, 160],
    background: [0, 0, 0, 1],
  },
  parameters: [
    {
      templateId: "color_primary",
      label: "Star Color A",
      group: "sketch",
      orderHint: 5,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [120, 60, 255],
      description: "Color of the first group of stars.",
    },
    {
      templateId: "color_secondary",
      label: "Star Color B",
      group: "sketch",
      orderHint: 6,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [0, 200, 255],
      description: "Color of the second group of stars.",
    },
    {
      templateId: "color_bg",
      label: "Trail Tint",
      group: "sketch",
      orderHint: 7,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 80, 160],
      description: "Tint blended into the tail of each trail.",
    },
    // Top 3
    {
      templateId: "trail_length",
      label: "Trail Length",
      group: "sketch",
      orderHint: 10,
      min: 0.1,
      max: 6.0,
      step: 0.05,
      defaultValue: 0.6,
      description:
        "How far back in time the trail extends. Higher = longer comet tails.",
    },
    {
      templateId: "trail_fade",
      label: "Trail Fade",
      group: "sketch",
      orderHint: 20,
      min: 0.5,
      max: 5.0,
      step: 0.05,
      defaultValue: 4.0,
      description:
        "How sharply the trail dims toward the tail. Low = long equal-brightness streak, high = tight comet head.",
    },
    {
      templateId: "star_glow",
      label: "Star Glow",
      group: "sketch",
      orderHint: 30,
      min: 0.003,
      max: 0.15,
      step: 0.002,
      defaultValue: 0.03,
      description:
        "Halo radius of each trail point — from laser-thin pinpricks to fat fog spheres.",
    },
    // Secondary
    {
      templateId: "star_brightness",
      label: "Brightness",
      group: "sketch",
      orderHint: 40,
      min: 0.5,
      max: 8.0,
      step: 0.1,
      defaultValue: 1.5,
      description: "Overall brightness of the stars and trails.",
    },
    {
      templateId: "swirl_speed",
      label: "Swirl Speed",
      group: "sketch",
      orderHint: 50,
      min: 0.0,
      max: 3.0,
      step: 0.05,
      defaultValue: 0.35,
      description: "How fast the stars orbit and drift.",
    },
    {
      templateId: "swirl_tightness",
      label: "Orbit Radius",
      group: "sketch",
      orderHint: 60,
      min: 0.05,
      max: 1.2,
      step: 0.01,
      defaultValue: 0.75,
      description:
        "Radius of the orbital paths. Low = tight spinning cluster, high = wide sweeping arcs.",
    },
    {
      templateId: "orbit_chaos",
      label: "Orbit Chaos",
      group: "sketch",
      orderHint: 70,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.33,
      description:
        "How much each star deviates from a perfect circle — adds Lissajous and speed variation.",
    },
    {
      templateId: "trail_smoke",
      label: "Smoke Scatter",
      group: "sketch",
      orderHint: 80,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.25,
      description:
        "Adds a wider soft scatter around each trail point — simulates light diffusing through fog.",
    },
    {
      templateId: "star_count",
      label: "Star Count",
      group: "sketch",
      orderHint: 90,
      min: 1,
      max: 8,
      step: 1,
      defaultValue: 5,
      inputType: "integer",
      description: "Number of stars (rebuilds shader).",
    },
    {
      templateId: "trail_steps",
      label: "Trail Steps",
      group: "sketch",
      orderHint: 100,
      min: 6,
      max: 28,
      step: 2,
      defaultValue: 10,
      description:
        "Trail quality — number of sample points per tail. Higher = smoother, more expensive (rebuilds shader).",
    },
    {
      templateId: "trail_blend",
      label: "Trail Blend",
      group: "sketch",
      orderHint: 105,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.6,
      description: "0 = distinct segmented look, 1 = seamless continuous line.",
    },
    {
      templateId: "three_body",
      label: "3-Body Chaos",
      group: "sketch",
      orderHint: 110,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.3,
      description: "Blends orbits from smooth ellipses (0) toward chaotic 3-body-like multi-frequency paths (1).",
    },
  ],
};
