import type { SketchDescriptor } from "@/sketches/types";
import thumbnail from "@/assets/sketches/dvd-thumb.png";

export const descriptor: SketchDescriptor = {
  thumbnail,
  id: "dvdBounce",
  label: "DVD Bounce",
  shortLabel: "DVD",
  description:
    "Classic DVD screensaver — a logo bounces around the screen and changes color on every edge hit. Upload your own image.",
  parameters: [
    {
      templateId: "dvd_image",
      label: "Logo Image",
      group: "sketch",
      orderHint: 5,
      min: 0,
      max: 0,
      step: 0,
      defaultValue: 0,
      inputType: "image",
      description: "Custom image to bounce. Defaults to DVD logo.",
    },
    {
      templateId: "dvd_speed",
      label: "Speed",
      group: "sketch",
      orderHint: 10,
      min: 0.1,
      max: 3,
      step: 0.05,
      defaultValue: 1,
      color: "cyan",
      description: "Bouncing speed of the logo.",
    },
    {
      templateId: "dvd_scale",
      label: "Size",
      group: "sketch",
      orderHint: 20,
      min: 0.05,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.18,
      color: "violet",
      description: "Logo size relative to viewport height.",
    },
    {
      templateId: "dvd_glow",
      label: "Glow",
      group: "sketch",
      orderHint: 30,
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.4,
      color: "amber",
      description: "Color glow bloom intensity.",
    },
    {
      templateId: "dvd_trail",
      label: "Trail",
      group: "sketch",
      orderHint: 40,
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0,
      color: "rose",
      description: "Motion trail opacity (0 = none).",
    },
  ],
};
