import type { SketchDescriptor } from "@/sketches/types";
import thumbnail from "@/assets/sketches/prismLines-thumb.png";

export const descriptor: SketchDescriptor = {
  thumbnail,
  id: "prismLines",
  label: "PrismLines",
  shortLabel: "PrismLines",
  description:
    "Glowing fog lines that crash and merge with prismatic flares at intersections (WebGPU/TSL).",
  colorPalette: {
    startColor: [0, 180, 255],
    midColor: [220, 0, 255],
    endColor: [0, 255, 120],
    background: [0, 0, 0, 1],
  },
  dynamicColorRange: {
    linkedParam: "pl_count",
    itemPrefix: "color_item",
  },
  parameters: [
    {
      templateId: "color_item1",
      label: "Line 1",
      group: "sketch",
      orderHint: 1,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [0, 180, 255],
      description: "Color of line 1.",
    },
    {
      templateId: "color_item2",
      label: "Line 2",
      group: "sketch",
      orderHint: 2,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [220, 0, 255],
      description: "Color of line 2.",
    },
    {
      templateId: "color_item3",
      label: "Line 3",
      group: "sketch",
      orderHint: 3,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [0, 255, 120],
      description: "Color of line 3.",
    },
    {
      templateId: "color_item4",
      label: "Line 4",
      group: "sketch",
      orderHint: 4,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 100, 0],
      description: "Color of line 4.",
    },
    {
      templateId: "color_item5",
      label: "Line 5",
      group: "sketch",
      orderHint: 5,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 0, 120],
      description: "Color of line 5.",
    },
    {
      templateId: "color_item6",
      label: "Line 6",
      group: "sketch",
      orderHint: 6,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [0, 220, 180],
      description: "Color of line 6.",
    },
    {
      templateId: "color_item7",
      label: "Line 7",
      group: "sketch",
      orderHint: 7,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 220, 0],
      description: "Color of line 7.",
    },
    {
      templateId: "color_item8",
      label: "Line 8",
      group: "sketch",
      orderHint: 8,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [100, 0, 255],
      description: "Color of line 8.",
    },
    {
      templateId: "color_bg",
      label: "Prism Tint",
      group: "sketch",
      orderHint: 9,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 220, 80],
      description: "Color tint added to the intersection / collision flare.",
    },
    {
      templateId: "line_glow",
      label: "Line Glow",
      group: "sketch",
      orderHint: 10,
      min: 0.001,
      max: 0.12,
      step: 0.001,
      defaultValue: 0.02,
      description:
        "Thickness / glow radius of each line. Very low = razor-thin light saber, high = fat fog beam.",
    },
    {
      templateId: "prism_intensity",
      label: "Prism Intensity",
      group: "sketch",
      orderHint: 20,
      min: 0.0,
      max: 5.0,
      step: 0.05,
      defaultValue: 2.2,
      description:
        "Strength of the rainbow flare emitted when two lines intersect.",
    },
    {
      templateId: "line_brightness",
      label: "Brightness",
      group: "sketch",
      orderHint: 30,
      min: 0.5,
      max: 8.0,
      step: 0.1,
      defaultValue: 1.0,
      description: "Overall brightness of the lines and flares.",
    },
    {
      templateId: "pl_speed",
      label: "Drift Speed",
      group: "sketch",
      orderHint: 40,
      min: 0.0,
      max: 2.0,
      step: 0.05,
      defaultValue: 0.25,
      description: "How fast lines drift and rotate across the scene.",
    },
    {
      templateId: "pl_count",
      label: "Line Count",
      group: "sketch",
      orderHint: 50,
      min: 2,
      max: 8,
      step: 1,
      defaultValue: 4,
      inputType: "integer",
      description: "Number of light lines. More lines = more intersections.",
    },
    {
      templateId: "smoke_density",
      label: "Smoke Density",
      group: "sketch",
      orderHint: 60,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.3,
      description: "How much the fog scatters light sideways along each beam.",
    },
    {
      templateId: "prism_spread",
      label: "Prism Spread",
      group: "sketch",
      orderHint: 70,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.35,
      description:
        "How wide the prismatic rainbow fans out from the intersection point.",
    },
    {
      templateId: "rotation_chaos",
      label: "Rotation Chaos",
      group: "sketch",
      orderHint: 80,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.5,
      description:
        "Each line rotates at its own speed. Higher = more chaotic angles and frequent crossings.",
    },
    {
      templateId: "chromatic_spread",
      label: "Chroma Spread",
      group: "sketch",
      orderHint: 90,
      min: 0.0,
      max: 0.15,
      step: 0.005,
      defaultValue: 0.02,
      description:
        "RGB channel separation on the lines — makes beams look refracted.",
    },
  ],
};
