import type { SketchDescriptor } from "@/sketches/types";
import thumbnail from "@/assets/sketches/wave-thumb.png";

export const descriptor: SketchDescriptor = {
  thumbnail,
  id: "waveform",
  label: "Waveform",
  shortLabel: "Wave",
  description:
    "Animated audio-style waveform visualization with multiple frequency bands and glow effects (WebGPU/TSL).",
  parameters: [
    {
      templateId: "wave_speed",
      label: "Speed",
      group: "sketch",
      orderHint: 10,
      min: 0,
      max: 3,
      step: 0.05,
      defaultValue: 1,
      color: "cyan",
      description: "Animation speed of the waveform.",
    },
    {
      templateId: "wave_amplitude",
      label: "Amplitude",
      group: "sketch",
      orderHint: 20,
      min: 0.1,
      max: 1,
      step: 0.05,
      defaultValue: 0.4,
      color: "lime",
      description: "Height/amplitude of the waves.",
    },
    {
      templateId: "wave_frequency",
      label: "Frequency",
      group: "sketch",
      orderHint: 30,
      min: 1,
      max: 10,
      step: 0.5,
      defaultValue: 4,
      color: "violet",
      description: "Number of wave cycles across the screen.",
    },
    {
      templateId: "wave_glow",
      label: "Glow",
      group: "sketch",
      orderHint: 40,
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.5,
      color: "amber",
      description: "Intensity of the glow effect around waves.",
    },
  ],
};
