import type { SketchDescriptor } from "../types";

export const descriptor: SketchDescriptor = {
  id: "vortexBeam",
  label: "VortexBeam",
  shortLabel: "VortexBeam",
  description:
    "Logarithmic spiral laser arms sweeping outward from the center, leaving glowing smoke trails — built for laser rigs and haze machines (WebGPU/TSL).",
  colorPalette: {
    startColor: [0, 255, 180],
    midColor: [120, 0, 255],
    endColor: [255, 60, 0],
    background: [0, 0, 0, 1],
  },
  parameters: [
    {
      templateId: "color_primary",
      label: "Beam Color",
      group: "sketch",
      orderHint: 5,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [0, 255, 180],
      description: "Primary beam color.",
    },
    {
      templateId: "color_secondary",
      label: "Tip Color",
      group: "sketch",
      orderHint: 6,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [120, 0, 255],
      description: "Color at the outer tip of each arm.",
    },
    {
      templateId: "color_bg",
      label: "Core Color",
      group: "sketch",
      orderHint: 7,
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 0,
      inputType: "color",
      defaultColorValue: [255, 60, 0],
      description: "Hot-core glow color at the center.",
    },
    // Top 3 live controls
    {
      templateId: "vb_speed",
      label: "Sweep Speed",
      group: "sketch",
      orderHint: 10,
      min: 0.0,
      max: 4.0,
      step: 0.05,
      defaultValue: 0.6,
      description: "How fast the spiral arms sweep around.",
    },
    {
      templateId: "vb_glow",
      label: "Beam Glow",
      group: "sketch",
      orderHint: 20,
      min: 0.002,
      max: 0.06,
      step: 0.001,
      defaultValue: 0.012,
      description: "Beam width — laser-thin to thick foggy bar.",
    },
    {
      templateId: "vb_brightness",
      label: "Brightness",
      group: "sketch",
      orderHint: 30,
      min: 0.5,
      max: 10.0,
      step: 0.1,
      defaultValue: 4.0,
      description: "Overall beam brightness.",
    },
    // Secondary
    {
      templateId: "vb_tightness",
      label: "Spiral Tightness",
      group: "sketch",
      orderHint: 40,
      min: 0.3,
      max: 4.0,
      step: 0.05,
      defaultValue: 1.4,
      description:
        "How tightly the arms coil. Low = loose open petals, high = dense spinning drill.",
    },
    {
      templateId: "vb_reach",
      label: "Reach",
      group: "sketch",
      orderHint: 50,
      min: 0.3,
      max: 1.5,
      step: 0.01,
      defaultValue: 0.9,
      description: "How far the arms extend from the center.",
    },
    {
      templateId: "vb_trail",
      label: "Trail Length",
      group: "sketch",
      orderHint: 60,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.55,
      description:
        "How much of the previous sweep lingers — low = sharp leading edge, high = full continuous spiral.",
    },
    {
      templateId: "vb_smoke",
      label: "Smoke Scatter",
      group: "sketch",
      orderHint: 70,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.4,
      description:
        "Adds wide soft glow simulating light scattering through real haze.",
    },
    {
      templateId: "vb_chroma",
      label: "Chroma Split",
      group: "sketch",
      orderHint: 80,
      min: 0.0,
      max: 0.04,
      step: 0.001,
      defaultValue: 0.01,
      description: "Chromatic aberration — splits beam edges into prismatic fringing.",
    },
    {
      templateId: "vb_pulse",
      label: "Pulse",
      group: "sketch",
      orderHint: 90,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.25,
      description: "Brightness pulsation — pairs with audio reactivity for beat sync.",
    },
    {
      templateId: "vb_arms",
      label: "Arm Count",
      group: "sketch",
      orderHint: 100,
      min: 1,
      max: 6,
      step: 1,
      defaultValue: 2,
      inputType: "integer",
      description: "Number of spiral arms (rebuilds shader). 1 = single scan, 2 = dual, up to 6.",
    },
  ],
};
