import type { EffectDescriptor } from "./effectTypes";

export const EFFECT_DESCRIPTORS: EffectDescriptor[] = [
  {
    id: "grain",
    label: "Film Grain",
    description: "Adds film grain noise texture",
    parameters: [
      {
        templateId: "intensity",
        label: "Intensity",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.4,
        color: "amber",
      },
    ],
  },
  {
    id: "bloom",
    label: "Bloom",
    description: "Glowing halo around bright areas",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: 1.0,
        color: "cyan",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.4,
        color: "sky",
      },
      {
        templateId: "threshold",
        label: "Threshold",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.85,
        color: "violet",
      },
    ],
  },
  {
    id: "rgb_shift",
    label: "RGB Shift",
    description: "Splits color channels",
    parameters: [
      {
        templateId: "amount",
        label: "Amount",
        min: 0,
        max: 0.02,
        step: 0.0005,
        defaultValue: 0.005,
        color: "rose",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 6.28,
        step: 0.01,
        defaultValue: 0,
        color: "indigo",
      },
    ],
  },
  {
    id: "chromatic_ab",
    label: "Chromatic Aberration",
    description: "Lens color fringing",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: 0.001,
        max: 0.02,
        step: 0.0005,
        defaultValue: 0.005,
        color: "fuchsia",
      },
    ],
  },
  {
    id: "blur",
    label: "Gaussian Blur",
    description: "Uniform blur",
    parameters: [
      {
        templateId: "sigma",
        label: "Sigma",
        min: 0,
        max: 8,
        step: 0.1,
        defaultValue: 2,
        color: "emerald",
      },
    ],
  },
  {
    id: "afterimage",
    label: "Afterimage",
    description: "Motion trails / feedback decay",
    parameters: [
      {
        templateId: "damp",
        label: "Damp",
        min: 0.8,
        max: 0.99,
        step: 0.005,
        defaultValue: 0.96,
        color: "lime",
      },
    ],
  },
  {
    id: "vignette",
    label: "Vignette",
    description: "Darkens edges of the frame",
    parameters: [
      {
        templateId: "smoothing",
        label: "Smoothing",
        min: 0.01,
        max: 0.8,
        step: 0.01,
        defaultValue: 0.25,
        color: "violet",
      },
      {
        templateId: "exponent",
        label: "Exponent",
        min: 1,
        max: 12,
        step: 0.1,
        defaultValue: 5,
        color: "indigo",
      },
    ],
  },
  {
    id: "crt",
    label: "CRT Scanlines",
    description: "CRT monitor scanlines + barrel distortion",
    parameters: [
      {
        templateId: "lineFrequency",
        label: "Frequency",
        min: 50,
        max: 500,
        step: 5,
        defaultValue: 200,
        color: "emerald",
      },
      {
        templateId: "lineIntensity",
        label: "Intensity",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.3,
        color: "lime",
      },
      {
        templateId: "curvature",
        label: "Curvature",
        min: 0,
        max: 0.5,
        step: 0.005,
        defaultValue: 0.1,
        color: "sky",
      },
      {
        templateId: "scanlineSharpness",
        label: "Sharpness",
        min: 0.05,
        max: 1,
        step: 0.01,
        defaultValue: 0.5,
        color: "cyan",
      },
    ],
  },
  {
    id: "dither",
    label: "Dither",
    description: "Bayer 8×8 ordered dithering",
    parameters: [
      {
        templateId: "pixelSize",
        label: "Pixel Size",
        min: 1,
        max: 16,
        step: 0.5,
        defaultValue: 2,
        color: "amber",
      },
      {
        templateId: "colorThreshold",
        label: "Colors",
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 4,
        color: "orange",
      },
      {
        templateId: "bias",
        label: "Bias",
        min: 0,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.25,
        color: "rose",
      },
    ],
  },
  {
    id: "halftone",
    label: "Halftone",
    description: "Print-style halftone dot pattern",
    parameters: [
      {
        templateId: "frequency",
        label: "Frequency",
        min: 10,
        max: 200,
        step: 1,
        defaultValue: 100,
        color: "fuchsia",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 3.14,
        step: 0.01,
        defaultValue: 0.5,
        color: "violet",
      },
      {
        templateId: "smoothness",
        label: "Smoothness",
        min: 0.01,
        max: 0.3,
        step: 0.005,
        defaultValue: 0.1,
        color: "indigo",
      },
    ],
  },
  {
    id: "led",
    label: "LED Screen",
    description: "Simulates an LED display panel",
    parameters: [
      {
        templateId: "scalar",
        label: "Density",
        min: 20,
        max: 300,
        step: 5,
        defaultValue: 100,
        color: "cyan",
      },
      {
        templateId: "zoom",
        label: "Zoom",
        min: 1,
        max: 5,
        step: 0.05,
        defaultValue: 2,
        color: "sky",
      },
      {
        templateId: "exponent",
        label: "Sharpness",
        min: 0.5,
        max: 3,
        step: 0.05,
        defaultValue: 1.2,
        color: "emerald",
      },
      {
        templateId: "edge",
        label: "Edge",
        min: 0.01,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.1,
        color: "lime",
      },
    ],
  },
  {
    id: "pixellation",
    label: "Pixellation",
    description: "Chunky pixel art downsampling",
    parameters: [
      {
        templateId: "size",
        label: "Size",
        min: 2,
        max: 100,
        step: 1,
        defaultValue: 20,
        color: "orange",
      },
    ],
  },
  {
    id: "bulge",
    label: "Bulge / Pinch",
    description: "Radial bulge or pinch distortion",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: -1,
        max: 1,
        step: 0.01,
        defaultValue: 0.5,
        color: "rose",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 0.1,
        max: 1,
        step: 0.01,
        defaultValue: 0.5,
        color: "amber",
      },
      {
        templateId: "power",
        label: "Power",
        min: 0.2,
        max: 3,
        step: 0.05,
        defaultValue: 1,
        color: "orange",
      },
    ],
  },
  {
    id: "swirl",
    label: "Swirl",
    description: "Rotational swirl distortion",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: -5,
        max: 5,
        step: 0.05,
        defaultValue: 1,
        color: "violet",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 0.1,
        max: 1.5,
        step: 0.01,
        defaultValue: 0.5,
        color: "indigo",
      },
    ],
  },
  {
    id: "wave",
    label: "Wave",
    description: "Animated sine-wave distortion",
    parameters: [
      {
        templateId: "frequency",
        label: "Frequency",
        min: 1,
        max: 30,
        step: 0.5,
        defaultValue: 10,
        color: "sky",
      },
      {
        templateId: "amplitude",
        label: "Amplitude",
        min: 0,
        max: 0.1,
        step: 0.001,
        defaultValue: 0.03,
        color: "cyan",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 6.28,
        step: 0.01,
        defaultValue: 0,
        color: "emerald",
      },
    ],
  },
];

export const EFFECT_DESCRIPTOR_MAP = new Map(
  EFFECT_DESCRIPTORS.map((d) => [d.id, d]),
);

export function getEffectDescriptor(
  effectId: string,
): EffectDescriptor | undefined {
  return EFFECT_DESCRIPTOR_MAP.get(effectId);
}

export function getEffectDefaultParams(effectId: string): Record<string, number> {
  const descriptor = EFFECT_DESCRIPTOR_MAP.get(effectId);
  if (!descriptor) return {};
  return Object.fromEntries(
    descriptor.parameters.map((p) => [p.templateId, p.defaultValue]),
  );
}
