import type { EffectDescriptor } from "./effectTypes";

export const EFFECT_DESCRIPTORS: EffectDescriptor[] = [
  {
    id: "grain",
    label: "Film Grain",
    description: "Adds film grain noise texture",
    parameters: [
      {
        templateId: "intensity",
        label: "Intensity",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 40,
        color: "amber",
        unit: "%",
      },
    ],
  },
  {
    id: "bloom",
    label: "Bloom",
    description: "Glowing halo around bright areas",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: 0,
        max: 300,
        step: 1,
        defaultValue: 100,
        color: "cyan",
        unit: "%",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 40,
        color: "sky",
        unit: "%",
      },
      {
        templateId: "threshold",
        label: "Threshold",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 85,
        color: "violet",
        unit: "%",
      },
    ],
  },
  {
    id: "rgb_shift",
    label: "RGB Shift",
    description: "Splits color channels",
    parameters: [
      {
        templateId: "amount",
        label: "Amount",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 25,
        color: "rose",
        unit: "%",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 0,
        color: "indigo",
        unit: "°",
      },
    ],
  },
  {
    id: "chromatic_ab",
    label: "Chromatic Aberration",
    description: "Lens color fringing",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: 0,
        max: 1000,
        step: 1,
        defaultValue: 25,
        color: "fuchsia",
        unit: "%",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 0,
        color: "violet",
        unit: "°",
      },
    ],
  },
  {
    id: "blur",
    label: "Gaussian Blur",
    description: "Uniform blur",
    parameters: [
      {
        templateId: "sigma",
        label: "Blur",
        min: 0,
        max: 8,
        step: 0.1,
        defaultValue: 2,
        color: "emerald",
      },
    ],
  },
  {
    id: "afterimage",
    label: "Afterimage",
    description: "Motion trails / feedback decay",
    parameters: [
      {
        templateId: "damp",
        label: "Persistence",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 84,
        color: "lime",
        unit: "%",
      },
    ],
  },
  {
    id: "vignette",
    label: "Vignette",
    description: "Darkens edges of the frame",
    parameters: [
      {
        templateId: "smoothing",
        label: "Smoothing",
        min: 1,
        max: 80,
        step: 1,
        defaultValue: 25,
        color: "violet",
        unit: "%",
      },
      {
        templateId: "exponent",
        label: "Hardness",
        min: 1,
        max: 12,
        step: 0.1,
        defaultValue: 5,
        color: "indigo",
      },
    ],
  },
  {
    id: "crt",
    label: "CRT Scanlines",
    description: "CRT monitor scanlines + barrel distortion",
    parameters: [
      {
        templateId: "lineFrequency",
        label: "Frequency",
        min: 50,
        max: 500,
        step: 5,
        defaultValue: 200,
        color: "emerald",
        unit: " lines",
      },
      {
        templateId: "lineIntensity",
        label: "Intensity",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 30,
        color: "lime",
        unit: "%",
      },
      {
        templateId: "curvature",
        label: "Curvature",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 20,
        color: "sky",
        unit: "%",
      },
      {
        templateId: "scanlineSharpness",
        label: "Sharpness",
        min: 5,
        max: 100,
        step: 1,
        defaultValue: 50,
        color: "cyan",
        unit: "%",
      },
    ],
  },
  {
    id: "dither",
    label: "Dither",
    description: "Bayer 8×8 ordered dithering",
    parameters: [
      {
        templateId: "pixelSize",
        label: "Pixel Size",
        min: 1,
        max: 16,
        step: 1,
        defaultValue: 2,
        color: "amber",
        unit: "px",
      },
      {
        templateId: "colorThreshold",
        label: "Colors",
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 4,
        color: "orange",
      },
      {
        templateId: "bias",
        label: "Bias",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 50,
        color: "rose",
        unit: "%",
      },
    ],
  },
  {
    id: "halftone",
    label: "Halftone",
    description: "Print-style halftone dot pattern",
    parameters: [
      {
        templateId: "frequency",
        label: "Frequency",
        min: 10,
        max: 200,
        step: 1,
        defaultValue: 100,
        color: "fuchsia",
      },
      {
        templateId: "angle",
        label: "Angle",
        min: 0,
        max: 180,
        step: 1,
        defaultValue: 29,
        color: "violet",
        unit: "°",
      },
      {
        templateId: "smoothness",
        label: "Smoothness",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 33,
        color: "indigo",
        unit: "%",
      },
    ],
  },
  {
    id: "led",
    label: "LED Screen",
    description: "Simulates an LED display panel",
    parameters: [
      {
        templateId: "scalar",
        label: "Density",
        min: 20,
        max: 300,
        step: 5,
        defaultValue: 100,
        color: "cyan",
      },
      {
        templateId: "zoom",
        label: "Zoom",
        min: 1,
        max: 5,
        step: 0.05,
        defaultValue: 2,
        color: "sky",
      },
      {
        templateId: "exponent",
        label: "Sharpness",
        min: 0.5,
        max: 3,
        step: 0.05,
        defaultValue: 1.2,
        color: "emerald",
      },
      {
        templateId: "edge",
        label: "Edge",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 20,
        color: "lime",
        unit: "%",
      },
    ],
  },
  {
    id: "pixellation",
    label: "Pixellation",
    description: "Chunky pixel art downsampling",
    parameters: [
      {
        templateId: "size",
        label: "Size",
        min: 2,
        max: 100,
        step: 1,
        defaultValue: 20,
        color: "orange",
        unit: "px",
      },
    ],
  },
  {
    id: "bulge",
    label: "Bulge / Pinch",
    description: "Radial bulge or pinch distortion",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: -100,
        max: 100,
        step: 1,
        defaultValue: 50,
        color: "rose",
        unit: "%",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 10,
        max: 100,
        step: 1,
        defaultValue: 50,
        color: "amber",
        unit: "%",
      },
      {
        templateId: "power",
        label: "Falloff",
        min: 0.2,
        max: 3,
        step: 0.05,
        defaultValue: 1,
        color: "orange",
      },
    ],
  },
  {
    id: "swirl",
    label: "Swirl",
    description: "Rotational swirl distortion",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: -100,
        max: 100,
        step: 1,
        defaultValue: 20,
        color: "violet",
        unit: "%",
      },
      {
        templateId: "radius",
        label: "Radius",
        min: 10,
        max: 150,
        step: 1,
        defaultValue: 50,
        color: "indigo",
        unit: "%",
      },
    ],
  },
  {
    id: "mirror",
    label: "Mirror",
    description: "Fold UV space horizontally and/or vertically",
    parameters: [
      {
        templateId: "horizontal",
        label: "Horizontal",
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 1,
        color: "sky",
        inputType: "toggle",
      },
      {
        templateId: "vertical",
        label: "Vertical",
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
        color: "indigo",
        inputType: "toggle",
      },
    ],
  },
  {
    id: "kaleidoscope",
    label: "Kaleidoscope",
    description: "Radial N-segment mirror symmetry",
    parameters: [
      {
        templateId: "segments",
        label: "Segments",
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 6,
        color: "violet",
      },
      {
        templateId: "zoom",
        label: "Zoom",
        min: 0.25,
        max: 4,
        step: 0.05,
        defaultValue: 1,
        color: "fuchsia",
      },
    ],
  },
  {
    id: "tile",
    label: "Tile",
    description: "Repeat output in a grid, with optional alternating mirror",
    parameters: [
      {
        templateId: "scale",
        label: "Scale",
        min: 1,
        max: 12,
        step: 0.1,
        defaultValue: 1,
        color: "emerald",
      },
      {
        templateId: "mirror",
        label: "Mirror",
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 1,
        color: "lime",
        inputType: "toggle",
      },
    ],
  },
  {
    id: "domain_warp",
    label: "Domain Warp",
    description: "FBM noise displaces UV, warping visuals into themselves",
    parameters: [
      {
        templateId: "strength",
        label: "Strength",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 30,
        color: "rose",
        unit: "%",
      },
      {
        templateId: "scale",
        label: "Scale",
        min: 0.5,
        max: 10,
        step: 0.1,
        defaultValue: 3,
        color: "orange",
      },
      {
        templateId: "octaves",
        label: "Octaves",
        min: 1,
        max: 6,
        step: 1,
        defaultValue: 3,
        color: "amber",
      },
      {
        templateId: "speed",
        label: "Speed",
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.3,
        color: "lime",
      },
      {
        templateId: "angle",
        label: "Drift Angle",
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 90,
        color: "sky",
        unit: "°",
      },
    ],
  },
];

export const EFFECT_DESCRIPTOR_MAP = new Map(
  EFFECT_DESCRIPTORS.map((d) => [d.id, d]),
);

export function getEffectDescriptor(
  effectId: string,
): EffectDescriptor | undefined {
  return EFFECT_DESCRIPTOR_MAP.get(effectId);
}

export function getEffectDefaultParams(
  effectId: string,
): Record<string, number> {
  const descriptor = EFFECT_DESCRIPTOR_MAP.get(effectId);
  if (!descriptor) return {};
  return Object.fromEntries(
    descriptor.parameters.map((p) => [p.templateId, p.defaultValue]),
  );
}
